export const initialBlobityOptions = {
  licenseKey: "opensource",
  focusableElementsOffsetX: 5,
  focusableElementsOffsetY: 5,
  color: "#e4ded7",
  dotColor: "#BCBCBC",
  invert: true,
  focusableElements:
    "[data-blobity], a:not([data-no-blobity]), h4:not([data-no-blobity]), li:not([data-no-blobity]), button:not([data-no-blobity]), [data-blobity-tooltip]",
  font: "'Montserrat','Source Sans Pro',-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,sans-serif",
  fontSize: 16,
  fontWeight: 500,
  borderRadius: "100px",
  opacity: 1,
  fontColor: "#BCBCBC",
  zIndex: 100,
  size: 40,
  radius: 25,
  magnetic: true,
};
